/*
 * VGAsprites.h
 *
 * Created: 29/08/2019 17:12:25
 *  Author: PETN
 */ 

#ifndef VGASPRITEDATA_H_
#define VGASPRITEDATA_H_
#include "usvc_kernel/vga.h"
#if GFX_MODE == TILE_MODE1
#include <stdint.h>
#define CARTYPE_REDCAR 0
#define CARTYPE_YELLOWCAR 1
#define CARTYPE_BLUECAR 2
#define CARTYPE_GREENCAR 3 
//
//
#define SPRITEDATA_NUMPIXELS 37562
#define FRAMEDATA_NUMFRAMES 99
#define ANIMDATA_NUMANIM 17
#define ENTITYDATA_NUMENTITIES 17
#define REDCAR 0
#define YELLOWCAR 1
#define EXPLOSION 2
#define BLUECAR 3
#define ROCKET 4
#define MINE 5
#define BONUSRANDOM 6
#define BONUSSPEED 7
#define BONUSTAKEN 8
#define WAIT 9
#define MINEINACTIVE 10
#define REMOTEBOMB 11
#define REDCARDESTROYED 12
#define YELLOWCARDESTROYED 13
#define BLUECARDESTROYED 14
#define GREENCAR 15
#define GREENCARDESTROYED 16
#define REDCAR_DEFAULTANIM 0
#define YELLOWCAR_DEFAULTANIM 0
#define EXPLOSION_DEFAULTANIM 0
#define BLUECAR_DEFAULTANIM 0
#define ROCKET_DEFAULTANIM 0
#define MINE_DEFAULTANIM 0
#define BONUSRANDOM_DEFAULTANIM 0
#define BONUSSPEED_DEFAULTANIM 0
#define BONUSTAKEN_DEFAULTANIM 0
#define WAIT_DEFAULTANIM 0
#define MINEINACTIVE_DEFAULTANIM 0
#define REMOTEBOMB_DEFAULTANIM 0
#define REDCARDESTROYED_DEFAULTANIM 0
#define YELLOWCARDESTROYED_DEFAULTANIM 0
#define BLUECARDESTROYED_DEFAULTANIM 0
#define GREENCAR_DEFAULTANIM 0
#define GREENCARDESTROYED_DEFAULTANIM 0
#define REDCAR_DEFAULTANIM_FRAMEINDEX 0x0000
#define YELLOWCAR_DEFAULTANIM_FRAMEINDEX 0x0005
#define EXPLOSION_DEFAULTANIM_FRAMEINDEX 0x000A
#define BLUECAR_DEFAULTANIM_FRAMEINDEX 0x0022
#define ROCKET_DEFAULTANIM_FRAMEINDEX 0x0027
#define MINE_DEFAULTANIM_FRAMEINDEX 0x0031
#define BONUSRANDOM_DEFAULTANIM_FRAMEINDEX 0x0033
#define BONUSSPEED_DEFAULTANIM_FRAMEINDEX 0x0036
#define BONUSTAKEN_DEFAULTANIM_FRAMEINDEX 0x0039
#define WAIT_DEFAULTANIM_FRAMEINDEX 0x0042
#define MINEINACTIVE_DEFAULTANIM_FRAMEINDEX 0x0048
#define REMOTEBOMB_DEFAULTANIM_FRAMEINDEX 0x0049
#define REDCARDESTROYED_DEFAULTANIM_FRAMEINDEX 0x004A
#define YELLOWCARDESTROYED_DEFAULTANIM_FRAMEINDEX 0x004F
#define BLUECARDESTROYED_DEFAULTANIM_FRAMEINDEX 0x0054
#define GREENCAR_DEFAULTANIM_FRAMEINDEX 0x0059
#define GREENCARDESTROYED_DEFAULTANIM_FRAMEINDEX 0x005E
#define REDCAR_DEFAULTANIM_NUMFRAMES 0x0005
#define YELLOWCAR_DEFAULTANIM_NUMFRAMES 0x0005
#define EXPLOSION_DEFAULTANIM_NUMFRAMES 0x0018
#define BLUECAR_DEFAULTANIM_NUMFRAMES 0x0005
#define ROCKET_DEFAULTANIM_NUMFRAMES 0x000A
#define MINE_DEFAULTANIM_NUMFRAMES 0x0002
#define BONUSRANDOM_DEFAULTANIM_NUMFRAMES 0x0003
#define BONUSSPEED_DEFAULTANIM_NUMFRAMES 0x0003
#define BONUSTAKEN_DEFAULTANIM_NUMFRAMES 0x0009
#define WAIT_DEFAULTANIM_NUMFRAMES 0x0006
#define MINEINACTIVE_DEFAULTANIM_NUMFRAMES 0x0001
#define REMOTEBOMB_DEFAULTANIM_NUMFRAMES 0x0001
#define REDCARDESTROYED_DEFAULTANIM_NUMFRAMES 0x0005
#define YELLOWCARDESTROYED_DEFAULTANIM_NUMFRAMES 0x0005
#define BLUECARDESTROYED_DEFAULTANIM_NUMFRAMES 0x0005
#define GREENCAR_DEFAULTANIM_NUMFRAMES 0x0005
#define GREENCARDESTROYED_DEFAULTANIM_NUMFRAMES 0x0005
//
#define GET_CAR_REAL_FRAME(carType, destroyed, angle) carFrames[2 * carType + ((destroyed) != 0)].pRealFrames[angle]
#define GET_CAR_ROTFLAGS(carType, destroyed, angle) carFrames[2 * carType + ((destroyed) != 0)].pRotationFlags[angle]
#define NUMBER_OF_DIFFERENT_CARS 4
typedef struct
{
	const uint8_t *pRealFrames;
	const uint8_t *pRotationFlags;
}car_frames_t;
typedef struct
{
	const uint16_t frameIndex;  //index to the first frame data
	const uint8_t numFrames;  //number of frames
} anim_t;
extern const uint8_t spriteData[SPRITEDATA_NUMPIXELS];
extern const frame_t frameData[FRAMEDATA_NUMFRAMES];
extern const anim_t animData[ANIMDATA_NUMANIM];
extern const anim_t* entityData[ENTITYDATA_NUMENTITIES];
extern const uint16_t entityAnimStartIndex[ENTITYDATA_NUMENTITIES];
extern const car_frames_t carFrames[2*NUMBER_OF_DIFFERENT_CARS];
#endif




#endif /* VGASPRITEDATA_H_ */